version: '3.1'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/books_crud
    ports:
      - 8002:8000
    image: books_crud:latest